name: Submit Feature
description: Request to list a new ACL Feature in specdir
title: "Add: "
labels: ["new-feature"]

body:
  - type: input
    id: feature_name
    attributes:
      label: Feature name
      placeholder: stripe.payments
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Feature Contract URL
      description: Stable public URL to your Feature Contract `.acl` file
      placeholder: https://yourdomain.com/features/stripe.payments/payments.contract.acl
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: One sentence describing what product slice this feature covers (max 120 chars)
    validations:
      required: true

  - type: dropdown
    id: maturity
    attributes:
      label: Maturity
      options:
        - draft
        - beta
        - stable
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: My URL is publicly reachable
          required: true
        - label: My file includes a valid `:::ACL_METADATA` block
          required: true
        - label: My domain in the entry matches the URL domain
          required: true
        - label: I have read CONTRIBUTING.md
          required: true
